[package]
authors = ["Erik Johnston"]
name = "matrix-federation"
version = "0.1.0"

[dependencies]
chrono = "0.2.19"
log = "0.3.5"
quick-error = "0.2.2"
rustc-serialize = "0.3.16"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.0"
sodiumoxide = "0.0.9"
